version: '3'

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - my-network
    volumes:
      - "./fastapi:/home/app"

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - my-network
    volumes:
      - "./streamlit:/home/app"

networks:
  my-network:
    driver: bridge