version: '3'

services:
  fastapi:
    build:
      context: ./FASTAPI
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./FASTAPI:/home/app" 

  streamlit:
    build:
      context: ./STREAMLIT
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - "./STREAMLIT:/home/app"
