name: Python application with sequential script execution

on:
  schedule:
    - cron: "0 2 * * 0" # Déclencher tous les dimanches à 2:00 AM UTC
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-update-csv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install schedule requests pandas scikit-learn spacy
        python -m spacy download en_core_web_sm
    - name: Run script_tmdb_api.py
      run: |
        python scripts/script_tmdb_api.py
    - name: Run script_imdb_rating.py
      run: |
        python scripts/script_imdb_rating.py
    - name: Run script_tmdb_content_based.py
      run: |
        python scripts/script_tmdb_content_based.py
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add fastapi/src/*
        git commit -m "Update CSV files"
        git push
